/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jason
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Creacion = new javax.swing.JDialog();
        jl_NombreMD = new javax.swing.JLabel();
        jl_NombreC = new javax.swing.JLabel();
        jl_EnergiaC = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_Nombre_r_c = new javax.swing.JLabel();
        jl_Cantidad_Vivas = new javax.swing.JLabel();
        jl_ObjetoMagico = new javax.swing.JLabel();
        jmb_Menu = new javax.swing.JMenuBar();
        jm_Login = new javax.swing.JMenu();
        jm_CrearD = new javax.swing.JMenu();

        jl_NombreMD.setText("Nombre del mundo");

        jl_NombreC.setText("Nombre de la Criatura");

        jl_EnergiaC.setText("Cantidad de energia vital");

        jLabel4.setText("Numero maximo de años de la criatura");

        jl_Nombre_r_c.setText("Nombre de la region de al criatura");

        jl_Cantidad_Vivas.setText("Cantidad de vivas de la especie");

        jl_ObjetoMagico.setText("Objecto magico");

        javax.swing.GroupLayout jd_CreacionLayout = new javax.swing.GroupLayout(jd_Creacion.getContentPane());
        jd_Creacion.getContentPane().setLayout(jd_CreacionLayout);
        jd_CreacionLayout.setHorizontalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NombreMD)
                    .addComponent(jl_NombreC)
                    .addComponent(jl_EnergiaC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jl_Nombre_r_c)
                    .addComponent(jl_Cantidad_Vivas)
                    .addComponent(jl_ObjetoMagico))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jd_CreacionLayout.setVerticalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_NombreMD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_NombreC)
                .addGap(18, 18, 18)
                .addComponent(jl_EnergiaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jl_Nombre_r_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_Cantidad_Vivas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_ObjetoMagico)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Login.setText("Login");
        jmb_Menu.add(jm_Login);

        jm_CrearD.setText("Crear un mundo disco");
        jm_CrearD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_CrearDActionPerformed(evt);
            }
        });
        jmb_Menu.add(jm_CrearD);

        setJMenuBar(jmb_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_CrearDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_CrearDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_CrearDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JDialog jd_Creacion;
    private javax.swing.JLabel jl_Cantidad_Vivas;
    private javax.swing.JLabel jl_EnergiaC;
    private javax.swing.JLabel jl_NombreC;
    private javax.swing.JLabel jl_NombreMD;
    private javax.swing.JLabel jl_Nombre_r_c;
    private javax.swing.JLabel jl_ObjetoMagico;
    private javax.swing.JMenu jm_CrearD;
    private javax.swing.JMenu jm_Login;
    private javax.swing.JMenuBar jmb_Menu;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Mundo_Disco> md = new ArrayList();
}
