/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jason
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Login = new javax.swing.JDialog();
        jl_Usuario = new javax.swing.JLabel();
        hl_Contraseña = new javax.swing.JLabel();
        bt_Login = new javax.swing.JButton();
        tf_Usuario = new javax.swing.JTextField();
        pd_Clave = new javax.swing.JPasswordField();
        jd_Agregar = new javax.swing.JDialog();
        cb_Mundos = new javax.swing.JComboBox<>();
        jl_Selc_M = new javax.swing.JLabel();
        bt_Aregar = new javax.swing.JButton();
        jl_Nombre = new javax.swing.JLabel();
        jl_Nombre_C_R = new javax.swing.JLabel();
        jl_Cant_C_E = new javax.swing.JLabel();
        jl_Numero_C = new javax.swing.JLabel();
        jl_Vivas_C = new javax.swing.JLabel();
        jl_Objeto_Magico = new javax.swing.JLabel();
        tf_Nombre_C = new javax.swing.JTextField();
        tf_Cant_E = new javax.swing.JTextField();
        tf_Numero_A = new javax.swing.JTextField();
        tf_Cant_Vivas = new javax.swing.JTextField();
        tf_Nombre_R = new javax.swing.JTextField();
        tf_Objeto_Magico = new javax.swing.JTextField();
        jd_Mostar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_3 = new javax.swing.JTextArea();
        jd_Eliminar = new javax.swing.JDialog();
        jd_Modificar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_1 = new javax.swing.JTextArea();
        jl_Opcion = new javax.swing.JLabel();
        jl_Modificacion = new javax.swing.JLabel();
        bt_Modificar = new javax.swing.JButton();
        tf_Op = new javax.swing.JTextField();
        tf_Modi = new javax.swing.JTextField();
        jd_Abrir = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_2 = new javax.swing.JTextArea();
        jmb_Menu = new javax.swing.JMenuBar();
        jm_Login = new javax.swing.JMenu();
        jm_CrearD = new javax.swing.JMenu();
        jm_Agregar_C = new javax.swing.JMenu();
        jm_Mostar = new javax.swing.JMenu();
        jm_Eliminar = new javax.swing.JMenu();
        jm_Modificar = new javax.swing.JMenu();
        jm_Abrir = new javax.swing.JMenu();
        jm_Guardar = new javax.swing.JMenu();

        jd_Login.setTitle("Login");

        jl_Usuario.setText("Ingrese usuario");

        hl_Contraseña.setText("Contraseña");

        bt_Login.setText("Login");
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(bt_Login))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hl_Contraseña)
                        .addGap(18, 18, 18)
                        .addComponent(pd_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hl_Contraseña)
                    .addComponent(pd_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(bt_Login)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        cb_Mundos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jl_Selc_M.setText("Seleccion de Mundo");

        bt_Aregar.setText("Agregar");
        bt_Aregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AregarMouseClicked(evt);
            }
        });

        jl_Nombre.setText("Nombre de la Criatura");

        jl_Nombre_C_R.setText("Nombre de la region");

        jl_Cant_C_E.setText("Cantidad de Energia Vital");

        jl_Numero_C.setText("Numero maximo de Años");

        jl_Vivas_C.setText("Cantidad de vivas de la especie");

        jl_Objeto_Magico.setText("Objeto Magico");

        javax.swing.GroupLayout jd_AgregarLayout = new javax.swing.GroupLayout(jd_Agregar.getContentPane());
        jd_Agregar.getContentPane().setLayout(jd_AgregarLayout);
        jd_AgregarLayout.setHorizontalGroup(
            jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_Aregar)
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Vivas_C)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Cant_Vivas))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Objeto_Magico)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Objeto_Magico))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Nombre_C_R)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Nombre_R))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Numero_C)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Numero_A))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Cant_C_E)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Cant_E))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Nombre_C))
                    .addGroup(jd_AgregarLayout.createSequentialGroup()
                        .addComponent(jl_Selc_M)
                        .addGap(30, 30, 30)
                        .addComponent(cb_Mundos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jd_AgregarLayout.setVerticalGroup(
            jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Mundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Selc_M))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(tf_Nombre_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cant_C_E)
                    .addComponent(tf_Cant_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Numero_C)
                    .addComponent(tf_Numero_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre_C_R)
                    .addComponent(tf_Nombre_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Vivas_C)
                    .addComponent(tf_Cant_Vivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Objeto_Magico)
                    .addComponent(tf_Objeto_Magico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_Aregar)
                .addContainerGap())
        );

        ta_3.setEditable(false);
        ta_3.setColumns(20);
        ta_3.setRows(5);
        jScrollPane1.setViewportView(ta_3);

        javax.swing.GroupLayout jd_MostarLayout = new javax.swing.GroupLayout(jd_Mostar.getContentPane());
        jd_Mostar.getContentPane().setLayout(jd_MostarLayout);
        jd_MostarLayout.setHorizontalGroup(
            jd_MostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        jd_MostarLayout.setVerticalGroup(
            jd_MostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_EliminarLayout = new javax.swing.GroupLayout(jd_Eliminar.getContentPane());
        jd_Eliminar.getContentPane().setLayout(jd_EliminarLayout);
        jd_EliminarLayout.setHorizontalGroup(
            jd_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_EliminarLayout.setVerticalGroup(
            jd_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ta_1.setEditable(false);
        ta_1.setColumns(20);
        ta_1.setRows(5);
        ta_1.setText("1. Nombre del mundo\n2. Nombre de la criatura\n3. Numero maximo de años\n4. Nombre de la region\n5. Cantidad de vivas de esa especie\n6. Objetos Maximos\n");
        jScrollPane2.setViewportView(ta_1);

        jl_Opcion.setText("Ingrese una opcion");

        jl_Modificacion.setText("Valor de modificacion");

        bt_Modificar.setText("Modificar");
        bt_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarLayout = new javax.swing.GroupLayout(jd_Modificar.getContentPane());
        jd_Modificar.getContentPane().setLayout(jd_ModificarLayout);
        jd_ModificarLayout.setHorizontalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jd_ModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_ModificarLayout.createSequentialGroup()
                                .addComponent(jl_Opcion)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Op))
                            .addGroup(jd_ModificarLayout.createSequentialGroup()
                                .addComponent(jl_Modificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_Modi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Modificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_ModificarLayout.setVerticalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Opcion)
                    .addComponent(tf_Op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Modificacion)
                    .addComponent(tf_Modi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(bt_Modificar)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        ta_2.setColumns(20);
        ta_2.setRows(5);
        jScrollPane3.setViewportView(ta_2);

        javax.swing.GroupLayout jd_AbrirLayout = new javax.swing.GroupLayout(jd_Abrir.getContentPane());
        jd_Abrir.getContentPane().setLayout(jd_AbrirLayout);
        jd_AbrirLayout.setHorizontalGroup(
            jd_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jd_AbrirLayout.setVerticalGroup(
            jd_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gran A’Tuin ");

        jm_Login.setText("Login");
        jm_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_LoginMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Login);

        jm_CrearD.setText("Crear un mundo disco");
        jm_CrearD.setEnabled(false);
        jm_CrearD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_CrearDMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_CrearD);

        jm_Agregar_C.setText("Agregar Criaturas");
        jm_Agregar_C.setEnabled(false);
        jm_Agregar_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_Agregar_CMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Agregar_C);

        jm_Mostar.setText("Mostrar");
        jm_Mostar.setEnabled(false);
        jm_Mostar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_MostarMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Mostar);

        jm_Eliminar.setText("Eliminar");
        jm_Eliminar.setEnabled(false);
        jm_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_EliminarMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Eliminar);

        jm_Modificar.setText("Modificar");
        jm_Modificar.setEnabled(false);
        jm_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_ModificarMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Modificar);

        jm_Abrir.setText("Abrir Archivo de texto");
        jm_Abrir.setEnabled(false);
        jm_Abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_AbrirMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Abrir);

        jm_Guardar.setText("Guardar Archivo");
        jm_Guardar.setEnabled(false);
        jm_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_GuardarMouseClicked(evt);
            }
        });
        jmb_Menu.add(jm_Guardar);

        setJMenuBar(jmb_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_LoginMouseClicked
        // TODO add your handling code here:
        jd_Login.setModal(true);
        jd_Login.pack();
        jd_Login.setLocationRelativeTo(this);
        jd_Login.setVisible(true);
    }//GEN-LAST:event_jm_LoginMouseClicked

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        try {
            MD2 = new Mundo_Disco_2("./Uuario");
            MD2.cargarArchivo();
            if (tf_Usuario.getText().equals(usuario)) {
                String clave = pd_Clave.getText(), nue = "";
                int a, n, llave = Integer.parseInt(pd_Clave.getText());
                char l;
                for (int i = 0; i < clave.length(); i++) {
                    a = clave.codePointAt(i);
                    if (a == 122) {
                        a = 65;
                    }
                    if (a == 90) {
                        a = 97;
                    }
                    n = a + llave;
                    l = (char) n;
                    nue += l;
                }//Fin del for 
                jm_Agregar_C.setEnabled(true);
                jm_CrearD.setEnabled(true);
                jm_Eliminar.setEnabled(true);
                jm_Mostar.setEnabled(true);
                jm_Modificar.setEnabled(true);
                jm_Abrir.setEnabled(true);
                jm_Guardar.setEnabled(true);
                MD2.escribirArchivo();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario Incorecto");
            }
        } catch (IOException e) {
        }
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void jm_CrearDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_CrearDMouseClicked
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(this, "Ingrese nombre del mundo");
        md = new Mundo_Disco(nombre);
        MD.add(md);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Mundos.getModel();
        modelo.addElement(md);
        cb_Mundos.setModel(modelo);
    }//GEN-LAST:event_jm_CrearDMouseClicked

    private void bt_AregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AregarMouseClicked
        // TODO add your handling code here:
        try {
            MD2 = new Mundo_Disco_2("./Mundos");
            c = new Criaturas(tf_Nombre_C.getText(), Double.parseDouble(tf_Cant_E.getText()), Integer.parseInt(tf_Numero_A.getText()), tf_Nombre_R.getText(), Integer.parseInt(tf_Cant_Vivas.getText()));
            ArrayList cria = new ArrayList();
            cria.add(c);
            md.setCria(cria);
            MD2.getCria().add(c);
            MD2.escribirArchivo();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bt_AregarMouseClicked

    private void jm_MostarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_MostarMouseClicked
        // TODO add your handling code here:
        jd_Mostar.setModal(true);
        jd_Mostar.pack();
        jd_Mostar.setLocationRelativeTo(this);
        jd_Mostar.setVisible(true);
    }//GEN-LAST:event_jm_MostarMouseClicked

    private void jm_Agregar_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_Agregar_CMouseClicked
        // TODO add your handling code here:
        jd_Agregar.setModal(true);
        jd_Agregar.pack();
        jd_Agregar.setLocationRelativeTo(this);
        jd_Agregar.setVisible(true);
    }//GEN-LAST:event_jm_Agregar_CMouseClicked

    private void jm_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_EliminarMouseClicked

    }//GEN-LAST:event_jm_EliminarMouseClicked

    private void jm_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_ModificarMouseClicked
        // TODO add your handling code here:
        jd_Modificar.setModal(true);
        jd_Modificar.pack();
        jd_Modificar.setLocationRelativeTo(this);
        jd_Modificar.setVisible(true);
    }//GEN-LAST:event_jm_ModificarMouseClicked

    private void bt_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ModificarMouseClicked
        // TODO add your handling code here:
        try {
            int op = Integer.parseInt(tf_Op.getText());
            String op2 = tf_Op.getText();
            if (op == 1 || op2.equals("nombre del disco")) {
                md.setNombre_t(tf_Modi.getText());
            } else if (op == 2 || op2.equalsIgnoreCase("nombre de la criatura")) {
                c.setNombre_c(tf_Modi.getText());
            } else if (op == 3 || op2.equals("cantidad de energia vital")) {
                c.setEnergia_v(Integer.parseInt(tf_Modi.getText()));
            } else if (op == 4 || op2.equalsIgnoreCase("numero maximo de años")) {
                c.setAños(Integer.parseInt(tf_Modi.getText()));
            } else if (op == 5) {
                
            } else if (op == 5) {
                
            } else {
                JOptionPane.showMessageDialog(this, "Opcion no valida");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_ModificarMouseClicked

    private void jm_AbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_AbrirMouseClicked
        // TODO add your handling code here:
        jd_Mostar.setModal(true);
        jd_Mostar.pack();
        jd_Mostar.setLocationRelativeTo(this);
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        ta_1.setText("");
        try {
            JFileChooser jfc = new JFileChooser("./Mundos");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
            jfc.setFileFilter(filtro);
            int selec = jfc.showOpenDialog(this);
            if (selec == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                ta_1.setText("");
                while ((linea = br.readLine()) != null) {
                    ta_1.append(linea);
                    ta_1.append("\n");
                }//Fin del while
            }//Fin del if
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (IOException e) {
        }
        jd_Mostar.setVisible(true);
    }//GEN-LAST:event_jm_AbrirMouseClicked

    private void jm_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_GuardarMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("./Mundos");
        FileNameExtensionFilter filt = new FileNameExtensionFilter("Archivos de texto", "txt");
        jfc.addChoosableFileFilter(filt);
        int selec = jfc.showSaveDialog(this);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (selec == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de Texto")) {
                    fichero = new File(jfc.getSelectedFile().getPath() + "txt");
                } else {
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                String nue = "";
                bw.write(tf_Usuario + "/" + nue + "/" + pd_Clave);
                pd_Clave.setText("");
                tf_Usuario.setText("");
                bw.flush();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jm_GuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Aregar;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Modificar;
    private javax.swing.JComboBox<String> cb_Mundos;
    private javax.swing.JLabel hl_Contraseña;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_Abrir;
    private javax.swing.JDialog jd_Agregar;
    private javax.swing.JDialog jd_Eliminar;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JDialog jd_Modificar;
    private javax.swing.JDialog jd_Mostar;
    private javax.swing.JLabel jl_Cant_C_E;
    private javax.swing.JLabel jl_Modificacion;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Nombre_C_R;
    private javax.swing.JLabel jl_Numero_C;
    private javax.swing.JLabel jl_Objeto_Magico;
    private javax.swing.JLabel jl_Opcion;
    private javax.swing.JLabel jl_Selc_M;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JLabel jl_Vivas_C;
    private javax.swing.JMenu jm_Abrir;
    private javax.swing.JMenu jm_Agregar_C;
    private javax.swing.JMenu jm_CrearD;
    private javax.swing.JMenu jm_Eliminar;
    private javax.swing.JMenu jm_Guardar;
    private javax.swing.JMenu jm_Login;
    private javax.swing.JMenu jm_Modificar;
    private javax.swing.JMenu jm_Mostar;
    private javax.swing.JMenuBar jmb_Menu;
    private javax.swing.JPasswordField pd_Clave;
    private javax.swing.JTextArea ta_1;
    private javax.swing.JTextArea ta_2;
    private javax.swing.JTextArea ta_3;
    private javax.swing.JTextField tf_Cant_E;
    private javax.swing.JTextField tf_Cant_Vivas;
    private javax.swing.JTextField tf_Modi;
    private javax.swing.JTextField tf_Nombre_C;
    private javax.swing.JTextField tf_Nombre_R;
    private javax.swing.JTextField tf_Numero_A;
    private javax.swing.JTextField tf_Objeto_Magico;
    private javax.swing.JTextField tf_Op;
    private javax.swing.JTextField tf_Usuario;
    // End of variables declaration//GEN-END:variables
  private String usuario = "xXxGranATuinxXx";
    private Mundo_Disco md;
    private Criaturas c;
    private ArrayList<Mundo_Disco> MD = new ArrayList();
    private Mundo_Disco_2 MD2;
}
